version: '3.7'

services:
  web:
    container_name: WannaChat
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/go/src/WannaChat
      - /go/src/WannaChat/vendor
    ports:
      - 8080:8080
    links:
      - db
  db:
    container_name: postgres
    image: postgres:12.1
    ports:
      - 5432:5432
